#version: '3.8'

services:
  postgres-primary:
    image: postgres:16
    container_name: postgres-primary
    restart: always
    environment:
      POSTGRES_USER: replicator
      POSTGRES_PASSWORD: your_replicator_password # Замените на надежный пароль
      POSTGRES_DB: your_database_name # Замените на имя вашей БД
      # Переменные для кастомизации конфига через environment
      # Они будут обработаны скриптом инициализации
    volumes:
      - primary_data:/var/lib/postgresql/data # Используем именованный том вместо bind mount
      - ./init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh # Скрипт инициализации
    ports:
      - "5433:5432" # Порт 5432 внутри контейнера мапится на 5433 на хосте
    networks:
      - postgres-replication

  postgres-replica:
    image: postgres:16
    container_name: postgres-replica
    restart: always
    environment:
      POSTGRES_USER: replicator
      POSTGRES_PASSWORD: your_replicator_password # Должен совпадать с primary
      POSTGRES_DB: your_database_name # Должен совпадать с primary
      PGHOST: postgres-primary
      PGUSER: replicator
      PGPASSWORD: your_replicator_password
    volumes:
      - replica_data:/var/lib/postgresql/data # Используем именованный том
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh # Скрипт инициализации реплики
    ports:
      - "5434:5432" # Порт 5432 внутри контейнера мапится на 5434 на хосте
    depends_on:
      - postgres-primary
    networks:
      - postgres-replication

volumes:
  primary_data:
  replica_data:

networks:
  postgres-replication:
    driver: bridge