# queries.yaml
pg_replication:
  query: |
    SELECT 
      pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn) AS lag_bytes,
      EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) AS lag_seconds
    FROM pg_stat_replication
  metrics:
    - lag_bytes:
        usage: "GAUGE"
        description: "Replication lag in bytes"
    - lag_seconds:
        usage: "GAUGE"
        description: "Replication lag in seconds"