global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres-primary'
    static_configs:
      - targets: ['pg_exporter_master:9187']
  
  - job_name: 'postgres-replica'
    static_configs:
      - targets: ['pg_exporter_replica:9187']