global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'postgres_master'
    static_configs:
      - targets: ['pg_exporter_master:9187']
  - job_name: 'postgres_phys'
    static_configs:
      - targets: ['pg_exporter_phys:9187']

  - job_name: 'postgres_cascade'
    static_configs:
      - targets: ['pg_exporter_cascade:9187']