global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'postgres_master'
    static_configs:
      - targets: ['pg_exporter_master:9187']
        
  - job_name: 'postgres_replica'
    static_configs:
      - targets: ['pg_exporter_replica:9187']
        
  - job_name: 'loadgen'
    static_configs:
      - targets: ['loadgen:2112']